name = "memos-worker"
compatibility_date = "2025-08-19"
main = "src/index.js"
[assets]
directory = "./src/public"
run_worker_first = [
	"/api/*"
]

[[d1_databases]]
binding = "DB"
database_id = "4bf0218d-80c6-44a2-b9c4-af2f12aab002"
database_name = "notes-db"

[[kv_namespaces]]
binding = "NOTES_KV"
id = "1e07afc0c5974012ac7b4bea0a09993c"
preview_id = ""

[[r2_buckets]]
binding = "NOTES_R2_BUCKET"
bucket_name = "notes-r2-bucket"
preview_bucket_name = "notes-files-preview"
