name = "memosworker"
compatibility_date = "2025-08-19"
main = "src/index.js"
[assets]
directory = "./src/public"
run_worker_first = [
	"/api/*"
]

[[d1_databases]]
binding = "DB"
database_id = "08225ee8-2f6f-4652-a589-7e3c0ae5b48a"
database_name = "notes-db"

[[kv_namespaces]]
binding = "NOTES_KV"
id = "b114a76a06514096a962d067582b84f7"
preview_id = ""

[[r2_buckets]]
binding = "NOTES_R2_BUCKET"
bucket_name = "notes-r2"
preview_bucket_name = "notes-files-preview"
